config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  resources :patient_cards
  resources :specializations
  resources :departments
  resources :clinics
  resources :doctors
  resources :patients
  resources :my_patients
  # get '/home', to: 'home#index'
  root 'home#index'
  # get '/users/edit', to: 'users#edit', as: :edit_user

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  # devise_scope :user do
  #   # ...
  #   get 'users/password/edit', to: 'devise/passwords#edit', as: :edit_user_password
  #   # ...
  # end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def update(attributes)
    super
  end
end

app/models/clinic.rb
class Clinic < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :clinic, class_name: 'Clinic', foreign_key: 'clinic_id'
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :department, class_name: 'Department', foreign_key: 'department_id'
end

app/models/doctors_view.rb
class DoctorsView < ApplicationRecord
  self.table_name = "doctors"
  self.ignored_columns = %w[created_at updated_at]
  self.primary_key = 'id'

  def readonly?
    true
  end

  def self.custom_query
    find_by_sql("
      SELECT id, name
      FROM doctors
    ")
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :patient_card
end

app/models/patient_card.rb
class PatientCard < ApplicationRecord
  belongs_to :clinic
end

app/models/patient_view.rb
class PatientView < ApplicationRecord
  self.table_name = "patients"
  self.ignored_columns = %w[created_at updated_at]
  self.primary_key = 'id'

  def readonly?
    true
  end

  def self.custom_query
    find_by_sql("
      SELECT id, name
      FROM patients
    ")
  end
end

app/models/specialization.rb
class Specialization < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  before_action :set_clinic, only: %i[ show edit update destroy ]

  # GET /clinics or /clinics.json
  def index
    @clinics = Clinic.all
  end

  # GET /clinics/1 or /clinics/1.json
  def show
  end

  # GET /clinics/new
  def new
    @clinic = Clinic.new
  end

  # GET /clinics/1/edit
  def edit
  end

  # POST /clinics or /clinics.json
  def create
    @clinic = Clinic.new(clinic_params)

    respond_to do |format|
      if @clinic.save
        format.html { redirect_to clinic_url(@clinic), notice: "Clinic was successfully created." }
        format.json { render :show, status: :created, location: @clinic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clinics/1 or /clinics/1.json
  def update
    respond_to do |format|
      if @clinic.update(clinic_params)
        format.html { redirect_to clinic_url(@clinic), notice: "Clinic was successfully updated." }
        format.json { render :show, status: :ok, location: @clinic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1 or /clinics/1.json
  def destroy
    @clinic.destroy

    respond_to do |format|
      format.html { redirect_to clinics_url, notice: "Clinic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clinic
      @clinic = Clinic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def clinic_params
      params.require(:clinic).permit(:name, :address, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/specializations_controller.rb
class SpecializationsController < ApplicationController
  before_action :set_specialization, only: %i[ show edit update destroy ]

  # GET /specializations or /specializations.json
  def index
    @specializations = Specialization.all
  end

  # GET /specializations/1 or /specializations/1.json
  def show
  end

  # GET /specializations/new
  def new
    @specialization = Specialization.new
  end

  # GET /specializations/1/edit
  def edit
  end

  # POST /specializations or /specializations.json
  def create
    @specialization = Specialization.new(specialization_params)

    respond_to do |format|
      if @specialization.save
        format.html { redirect_to specialization_url(@specialization), notice: "Specialization was successfully created." }
        format.json { render :show, status: :created, location: @specialization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @specialization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specializations/1 or /specializations/1.json
  def update
    respond_to do |format|
      if @specialization.update(specialization_params)
        format.html { redirect_to specialization_url(@specialization), notice: "Specialization was successfully updated." }
        format.json { render :show, status: :ok, location: @specialization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @specialization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specializations/1 or /specializations/1.json
  def destroy
    @specialization.destroy

    respond_to do |format|
      format.html { redirect_to specializations_url, notice: "Specialization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialization
      @specialization = Specialization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def specialization_params
      params.require(:specialization).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/my_patients_helper.rb
module MyPatientsHelper
end

app/helpers/patient_cards_helper.rb
module PatientCardsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/specializations_helper.rb
module SpecializationsHelper
end

app/views/specializations/_form.html.erb
<%= form_with(model: specialization) do |form| %>
  <% if specialization.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(specialization.errors.count, "error") %> prohibited this specialization from being saved:</h2>

      <ul>
        <% specialization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/specializations/_specialization.html.erb
<div id="<%= dom_id specialization %>">
  <p>
    <strong>Name:</strong>
    <%= specialization.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= specialization.description %>
  </p>

</div>

app/views/specializations/edit.html.erb
<h1>Editing specialization</h1>

<%= render "form", specialization: @specialization %>

<br>

<div>
  <%= link_to "Show this specialization", @specialization %> |
  <%= link_to "Back to specializations", specializations_path %>
</div>

app/views/specializations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Specializations</h1>


<div id="specializations">
  <table class="table table table-striped table table-bordered table table-hover">
    <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @specializations.each do |specialization| %>
      <tr>
        <td><%= specialization.name %></td>
        <td><%= specialization.description %></td>
        <td>
          <%= link_to "Edit", edit_specialization_path(specialization), class:"btn btn-secondary" %>
          <%= link_to "Delete", specialization_path(specialization), class:"btn btn-secondary", method: :delete, data: { confirm: "Are you sure?" } %>
          <%#= link_to "Show", specialization %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%= link_to "Create NewSpecialization", new_specialization_path, class:"btn btn-secondary" %>

app/views/specializations/new.html.erb
<h1>New specialization</h1>

<%= render "form", specialization: @specialization %>

<br>

<div>
  <%= link_to "Back to specializations", specializations_path %>
</div>

app/views/specializations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @specialization %>

<div>
  <%= link_to "Edit this specialization", edit_specialization_path(@specialization) %> |
  <%= link_to "Back to specializations", specializations_path %>

  <%= button_to "Destroy this specialization", @specialization, method: :delete %>
</div>