config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  resources :patient_cards
  resources :specializations
  resources :departments
  resources :clinics
  resources :doctors
  resources :patients
  resources :my_patients
  # get '/home', to: 'home#index'
  root 'home#index'
  # get '/users/edit', to: 'users#edit', as: :edit_user

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  # devise_scope :user do
  #   # ...
  #   get 'users/password/edit', to: 'devise/passwords#edit', as: :edit_user_password
  #   # ...
  # end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def update(attributes)
    super
  end
end

app/models/clinic.rb
class Clinic < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :clinic, class_name: 'Clinic', foreign_key: 'clinic_id'
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :department, class_name: 'Department', foreign_key: 'department_id'
end

app/models/doctors_view.rb
class DoctorsView < ApplicationRecord
  self.table_name = "doctors"
  self.ignored_columns = %w[created_at updated_at]
  self.primary_key = 'id'

  def readonly?
    true
  end

  def self.custom_query
    find_by_sql("
      SELECT id, name
      FROM doctors
    ")
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :patient_card
end

app/models/patient_card.rb
class PatientCard < ApplicationRecord
  belongs_to :clinic
end

app/models/patient_view.rb
class PatientView < ApplicationRecord
  self.table_name = "patients"
  self.ignored_columns = %w[created_at updated_at]
  self.primary_key = 'id'

  def readonly?
    true
  end

  def self.custom_query
    find_by_sql("
      SELECT id, name
      FROM patients
    ")
  end
end

app/models/specialization.rb
class Specialization < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  before_action :set_clinic, only: %i[ show edit update destroy ]

  # GET /clinics or /clinics.json
  def index
    @clinics = Clinic.all
  end

  # GET /clinics/1 or /clinics/1.json
  def show
  end

  # GET /clinics/new
  def new
    @clinic = Clinic.new
  end

  # GET /clinics/1/edit
  def edit
  end

  # POST /clinics or /clinics.json
  def create
    @clinic = Clinic.new(clinic_params)

    respond_to do |format|
      if @clinic.save
        format.html { redirect_to clinic_url(@clinic), notice: "Clinic was successfully created." }
        format.json { render :show, status: :created, location: @clinic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clinics/1 or /clinics/1.json
  def update
    respond_to do |format|
      if @clinic.update(clinic_params)
        format.html { redirect_to clinic_url(@clinic), notice: "Clinic was successfully updated." }
        format.json { render :show, status: :ok, location: @clinic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1 or /clinics/1.json
  def destroy
    @clinic.destroy

    respond_to do |format|
      format.html { redirect_to clinics_url, notice: "Clinic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clinic
      @clinic = Clinic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def clinic_params
      params.require(:clinic).permit(:name, :address, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/my_patients_helper.rb
module MyPatientsHelper
end

app/helpers/patient_cards_helper.rb
module PatientCardsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'MyHospital App', root_path, class:"navbar-brand" %>
<!--  <a class="navbar-brand" href="#"></a>-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">

          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Settings", edit_user_registration_path, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item active">
        <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Tables
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Clinics", clinics_path, class: "dropdown-item" %>
          <%= link_to "Doctors", doctors_path, class: "dropdown-item" %>
          <%= link_to "Patients", patients_path, class: "dropdown-item" %>
          <%= link_to "Departments", departments_path, class: "dropdown-item" %>
          <%= link_to "Patients Cards", patient_cards_path, class: "dropdown-item" %>
          <%= link_to "Specializations", specializations_path, class: "dropdown-item" %>
<!--          <a class="dropdown-item" href="#">Action1</a>-->
<!--          <a class="dropdown-item" href="#">Another action</a>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
        </div>
<!--      </li>-->
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--      </li>-->
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/index.html.erb
<!--<h1>Main</h1>-->
<%# if user_signed_in? %>
  <%#= link_to 'Выйти', destroy_user_session_path, method: :delete %>
  <%#= link_to 'Изменить', edit_user_registration_path%>
<%# else %>
  <%#= link_to 'Войти', new_user_session_path %>
  <%#= link_to 'Зарегистрироваться', new_user_registration_path %>
  <%#= link_to 'Забыли пароль?', new_user_password_path %>
<%# end %>