config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  resources :patient_cards
  resources :specializations
  resources :departments
  resources :clinics
  resources :doctors
  resources :patients
  resources :my_patients
  # get '/home', to: 'home#index'
  root 'home#index'
  # get '/users/edit', to: 'users#edit', as: :edit_user

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  # devise_scope :user do
  #   # ...
  #   get 'users/password/edit', to: 'devise/passwords#edit', as: :edit_user_password
  #   # ...
  # end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def update(attributes)
    super
  end
end

app/models/clinic.rb
class Clinic < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :clinic, class_name: 'Clinic', foreign_key: 'clinic_id'
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :department, class_name: 'Department', foreign_key: 'department_id'
end

app/models/doctors_view.rb
class DoctorsView < ApplicationRecord
  self.table_name = "doctors"
  self.ignored_columns = %w[created_at updated_at]
  self.primary_key = 'id'

  def readonly?
    true
  end

  def self.custom_query
    find_by_sql("
      SELECT id, name
      FROM doctors
    ")
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :patient_card
end

app/models/patient_card.rb
class PatientCard < ApplicationRecord
  belongs_to :clinic
end

app/models/patient_view.rb
class PatientView < ApplicationRecord
  self.table_name = "patients"
  self.ignored_columns = %w[created_at updated_at]
  self.primary_key = 'id'

  def readonly?
    true
  end

  def self.custom_query
    find_by_sql("
      SELECT id, name
      FROM patients
    ")
  end
end

app/models/specialization.rb
class Specialization < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  before_action :set_clinic, only: %i[ show edit update destroy ]

  # GET /clinics or /clinics.json
  def index
    @clinics = Clinic.all
  end

  # GET /clinics/1 or /clinics/1.json
  def show
  end

  # GET /clinics/new
  def new
    @clinic = Clinic.new
  end

  # GET /clinics/1/edit
  def edit
  end

  # POST /clinics or /clinics.json
  def create
    @clinic = Clinic.new(clinic_params)

    respond_to do |format|
      if @clinic.save
        format.html { redirect_to clinic_url(@clinic), notice: "Clinic was successfully created." }
        format.json { render :show, status: :created, location: @clinic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clinics/1 or /clinics/1.json
  def update
    respond_to do |format|
      if @clinic.update(clinic_params)
        format.html { redirect_to clinic_url(@clinic), notice: "Clinic was successfully updated." }
        format.json { render :show, status: :ok, location: @clinic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1 or /clinics/1.json
  def destroy
    @clinic.destroy

    respond_to do |format|
      format.html { redirect_to clinics_url, notice: "Clinic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clinic
      @clinic = Clinic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def clinic_params
      params.require(:clinic).permit(:name, :address, :phone)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: %i[ show edit update destroy ]

  # GET /doctors or /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1 or /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors or /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully created." }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1 or /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully updated." }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1 or /doctors/1.json
  def destroy
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url, notice: "Doctor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_params
      params.require(:doctor).permit(:name, :age, :gender, :department_id_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :age, :gender, :patient_card_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/my_patients_helper.rb
module MyPatientsHelper
end

app/helpers/patient_cards_helper.rb
module PatientCardsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/specializations_helper.rb
module SpecializationsHelper
end

app/views/doctors/_doctor.html.erb
<div id="<%= dom_id doctor %>">
  <p>
    <strong>Name:</strong>
    <%= doctor.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= doctor.age %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= doctor.gender %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= doctor.department_id %>
  </p>

</div>

app/views/doctors/_form.html.erb
<%= form_with(model: doctor) do |form| %>
  <% if doctor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
        <% doctor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :department_id, style: "display: block" %>
    <%= form.text_field :department_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render "form", doctor: @doctor %>

<br>

<div>
  <%= link_to "Show this doctor", @doctor %> |
  <%= link_to "Back to doctors", doctors_path %>
</div>

app/views/doctors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Doctors</h1>


<div id="doctors">
  <table class="table table table-striped table table-bordered table table-hover">
    <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Gender</th>
      <th>DepartID</th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.age %></td>
        <td><%= doctor.gender %></td>
        <td><%= doctor.department_id %></td>
        <td>
          <%= link_to "Edit", edit_doctor_path(doctor), class:"btn btn-secondary" %>
          <%= link_to "Delete", doctor_path(doctor), class:"btn btn-secondary", method: :delete, data: { confirm: "Are you sure?" } %>
          <%#= link_to "Show", doctor %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%= link_to "Create NewDocotor", new_doctor_path, class:"btn btn-secondary" %>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render "form", doctor: @doctor %>

<br>

<div>
  <%= link_to "Back to doctors", doctors_path %>
</div>

app/views/doctors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @doctor %>

<div>
  <%= link_to "Edit this doctor", edit_doctor_path(@doctor) %> |
  <%= link_to "Back to doctors", doctors_path %>

  <%= button_to "Destroy this doctor", @doctor, method: :delete %>
</div>

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :patient_card_id, style: "display: block" %>
    <%= form.text_field :patient_card_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>">
  <p>
    <strong>Name:</strong>
    <%= patient.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= patient.age %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= patient.gender %>
  </p>

  <p>
    <strong>Patient card:</strong>
    <%= patient.patient_card_id %>
  </p>

</div>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
<!--  <%#= link_to "Show this patient", @patient %> |-->
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Patients</h1>


<div id="patients">
<table class="table table table-striped table table-bordered table table-hover">
  <thead class="thead-dark">
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Gender</th>
    <th>Actions</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
      <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.age %></td>
        <td><%= patient.gender %></td>
        <td>
          <%= link_to "Edit", edit_patient_path(patient), class:"btn btn-secondary" %>
          <%= link_to "Delete", patient_path(patient), class:"btn btn-secondary", method: :delete, data: { confirm: "Are you sure?" } %>
          <%#= link_to "Show", patient %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>
</div>

<%= link_to "Create NewPatient", new_patient_path, class:"btn btn-secondary" %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @patient %>

<div>
  <%= link_to "Edit this patient", edit_patient_path(@patient) %> |
  <%= link_to "Back to patients", patients_path %>

  <%= button_to "Destroy this patient", @patient, method: :delete %>
</div>